### ISSUE TITLE
Add container environment variables use case

### ISSUE THREAD

**Issue by kk2526** [yogeshkk/K8sPurger#4]
https://kubernetes.io/docs/concepts/configuration/secret/#use-cases

Need to take into account below scenario and have it append to UsedSecret/UsedConfigMap function.
```
    spec:
      containers:
      - env:
        envFrom:
        - configMapRef:
            name: configmap-test
        - secretRef:
            name: secrets-test
```

below is the block that will get you all the names of those secrets
```
                if item.env_from is not None:
                    for envfrom in item.env_from:
                        if envfrom.secret_ref is not None:
                            UsedSecret.append(
                                    [envfrom.secret_ref.name, i.metadata.namespace])
```

**Comment by yogeshkk** [comment]
@kk2526 That code is to handle below and it handle both configmap and secret 

```
        - name: my_env
           valueFrom:
             secretKeyRef:
                name: secret1
                key: my_env
```

The link you provided have different way to defining env(refer below). look like it handled different internally in k8s. I will visit that and make modification in script.

```
      envFrom:
      - secretRef:
          name: mysecret
```
