### ISSUE TITLE
If you know a short way

### ISSUE THREAD

**Issue by estahn** [yogeshkk/K8sPurger#9]
@yogeshkk We're using a combination of [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) and [kube-janitor](https://codeberg.org/hjacobs/kube-janitor) to achieve this.

The ArgoCD application resource gets a timestamp through CI/CD:

```
---
apiVersion: argoproj.io/v1alpha1
metadata:
  name: 'foobar-{{ getenv "GIT_BRANCH" | strings.Slug }}'
  annotations:
    janitor/expires: '{{ ((time.Now).Add (time.Hour 24)).UTC.Format "2006-01-02" }}T12:00:00Z'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
```

Janitor will then clean up resources after 24h.
